### PR TITLE
Bump Docker client API to fix compatibility with Docker version 25

### LINKED ISSUE #431: Urgent: DPS breaks after upgrade to docker-ce version >25
### What is Happening / What is expected
* Please describe how to reproduce the issue with a minimal example
Upgrade docker-ce to version 25 and above, DSP will stop working due to outdated client API version.

`client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

* Describe what you expected to happen and why
upgrade client libs to meet the dependencies of docker API

### Specs
* OS: Debian Bullseye
* Docker Version: 25
* DPS Version: docker image latest (0f1a63d45c2f)
* Attach DPS Log file

> WAR c.m.d.dnsconfigurator.DnsConfigurators            l=58   m=lambda$configurationHook$0      status=failedToConfigureAsDefaultDns, path=/host/etc/systemd/resolved.conf,/host/et
> c/resolv.conf,/etc/systemd/resolved.conf,/etc/resolv.conf, msg=Status 400: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
>                                                                                                                                                                                                                  
> com.github.dockerjava.api.exception.BadRequestException: Status 400: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### PR DESCRIPTION
**Pull request by ThisIsQasim**
Fixes #431 

[Tests are passing](https://github.com/ThisIsQasim/dns-proxy-server/actions/runs/7669451043)

### CODE REVIEW

**Comment by ThisIsQasim** [comment]
Hey @mageddo, Docker pushed version 25 a few days ago and that broke compatibility. Would appreciate if you could take a look and create a release. Thanks!

**Review by cmiguelcabral — APPROVED** [review]
Tested and working

**Comment by friimaind** [comment]
Can we push this PR please?

**Comment by mageddo** [comment]
Hey, I'm merging it in the next hours.

**Review by mageddo — APPROVED** [review]

**Comment by mageddo** [comment]
It was released, thanks for the contribution

**Pull request merged**
